import { css } from '../../../../styled-system/css';

export const markdownContentStyles = css({
  '& h1': {
    textStyle: 'h1',
    mt: '8',
    mb: '6',
    pb: '2',
    borderBottomWidth: 'thin',
    borderBottomStyle: 'solid',
    borderColor: 'border.default',
    color: 'text.default',
  },
  '& h2': {
    textStyle: 'h2',
    mt: '8',
    mb: '5',
    color: 'text.default',
  },
  '& h3': {
    textStyle: 'h3',
    mt: '6',
    mb: '4',
    color: 'text.default',
  },
  '& p': {
    textStyle: 'body',
    mb: '5',
    color: 'text.muted',
    textWrap: 'pretty',
  },
  '& ul': { listStyleType: 'disc', pl: '5', mb: '5', color: 'text.muted' },
  '& ol': { listStyleType: 'decimal', pl: '5', mb: '5', color: 'text.muted' },
  '& li': { mb: '2' },
  '& a': {
    color: 'link.default',
    textDecoration: 'underline',
    _hover: { color: 'link.hover' },
  },
  '& code': {
    fontFamily: 'mono',
    bg: 'bg.subtle',
    color: 'accent.default',
    px: '1.5',
    py: '0.5',
    borderRadius: 'sm',
    fontSize: '0.9em',
    fontWeight: 'medium',
  },
  '& pre': {
    bg: 'bg.muted',
    p: '4',
    borderRadius: 'md',
    overflowX: 'auto',
    borderWidth: 'thin',
    borderStyle: 'solid',
    borderColor: 'border.muted',
    fontSize: 'sm',
    lineHeight: 'relaxed',
    maxWidth: 'full',
    my: '8',
    fontFamily: 'mono',
    '& code': {
      bg: 'transparent',
      p: 0,
      color: 'inherit',
      fontSize: 'inherit',
      fontWeight: 'inherit',
      display: 'block',
      wordBreak: 'break-all',
      overflowWrap: 'break-word',
    },
  },
  '& [data-rehype-pretty-code-figure]': {
    my: '8',
    '& [data-rehype-pretty-code-title]': {
      bg: 'bg.muted',
      color: 'text.muted',
      fontSize: 'xs',
      fontFamily: 'mono',
      px: '4',
      py: '2',
      borderTopRadius: 'md',
      borderXWidth: 'thin',
      borderTopWidth: 'thin',
      borderStyle: 'solid',
      borderColor: 'border.muted',
    },
    '& pre': {
      my: '0',
      '&[data-has-title]': {
        borderTopRadius: 'none',
      },
    },
    '& code': {
      display: 'grid',
    },
    '& [data-highlighted-line]': {
      bg: 'overlay.light',
      borderLeftWidth: 'medium',
      borderLeftStyle: 'solid',
      borderColor: 'accent.default',
      mx: '-4',
      px: '4',
    },
  },
  '& blockquote': {
    borderLeftWidth: 'thick',
    borderLeftStyle: 'solid',
    borderColor: 'border.default',
    pl: '4',
    py: '1',
    fontStyle: 'italic',
    color: 'text.muted',
    my: '6',
  },
  '& table': {
    w: 'full',
    borderCollapse: 'collapse',
    mb: '8',
    display: 'block',
    overflowX: 'auto',
  },
  '& th': {
    borderBottomWidth: 'medium',
    borderBottomStyle: 'solid',
    borderColor: 'border.default',
    px: '4',
    py: '3',
    textAlign: 'left',
    fontWeight: 'bold',
    color: 'text.default',
  },
  '& td': {
    borderBottomWidth: 'thin',
    borderBottomStyle: 'solid',
    borderColor: 'border.muted',
    px: '4',
    py: '3',
    color: 'text.muted',
  },
  '& figure': {
    my: '8',
    mx: '0',
  },
});
